const givenName = [
  "Jacoby",
  "Samwell",
  "Percival",
  "Aevis ",
  "Grace",
  "Gregor",
  "Margery",
  "Beatrix",
  "Laylah",
  "Fortune",
  "Donovan",
  "Ursula ",
  "Eliphas",
  "Tomothy",
  "Arthur",
  "Marion",
  "Livery",
  "Agnes",
  "Billiam",
  "Bartholomew",
  "Evelyn",
  "Solomon ",
  "Maud",
  "Oswyn ",
  "Stella",
  "Valentine",
  "Ophelia",
  "Julian",
  "Florence",
  "Euston",
  "Daisley",
  "Bernard ",
  "Lucien",
  "Cuthbert",
  "Manly",
  "Ambrose ",
  "Kenneth",
  "Winifred",
  "Steffi",
  "Lettice",
  "Arrington",
  "Parnell",
  "Damien",
  "Wilmot",
  "Egg",
  "Constance",
  "Jack",
  "Alice",
  "Ursula",
  "Ethelred",
];

const surname = [
  "Molensis",
  "Perricoat",
  "Bourgeois",
  "Sartorius",
  "Canterbury",
  "Sharman",
  "Virtus",
  "Gardynium",
  "Daw",
  "Snayth",
  "Paddock",
  "Spebbington",
  "Mendacium",
  "Pontificate",
  "Yeats",
  "Gysborne",
  "Underhill",
  "Guildeforde",
  "Matutina",
  "Aumberden",
  "Gonne",
  "Mortymer",
  "Farrcaster",
  "Hadresham",
  "Machen",
  "Cox",
  "Waite",
  "Barabajagal",
  "Giffin",
  "Whowood",
  "Mathers",
  "Yornold",
  "Havelock",
  "DeSantis",
  "Steiner",
  "Yelverton",
  "Regardie",
  "Leventhorpe",
  "Weiser",
  "Frogenhall",
  "Dent",
  "Brecknock",
  "Makepiece",
  "Erewaker",
  "Dupin",
  "Dygenys",
  "Sodom",
  "Cranegrave",
  "Midcap",
  "Godmass",
];

export function RandomName() {
  const randomGivenName =
    givenName[Math.floor(Math.random() * givenName.length)];
  const randomSurname = surname[Math.floor(Math.random() * surname.length)];

  return <>{`${randomGivenName} ${randomSurname}`}</>;
}
